build/version.go, build/version_test.go, publish.sh, rivined/server.go
=> add version string parse support

.gitignore, Makefile, release.sh
=> clean up Makefile

api/server_helpers_test.go, api/wallet_test.go, modules/blockcreator/proofofblockstake_test.go, modules/consensus/accept_test.go, modules/consensus/block_validation_test.go, modules/consensus/diffs_test.go, modules/consensus/validtransaction_test.go, modules/explorer/info_test.go, modules/transactionpool/accept_test.go, modules/transactionpool/subscribe_test.go, modules/wallet/transactionbuilder_test.go, types/block.go, types/block_test.go, types/signatures_test.go, types/target_test.go, types/transactions_test.go, types/validtransaction_bench_test.go, types/validtransaction_test.go
```
$ pwd
... /go/src/github.com/rivine/rivine/types
$ go test -tags='debug testing' -v .
...
PASS
ok  	github.com/rivine/rivine/types	0.021s
```
=> Fix unit tests: types package 

.travis.yml, Gopkg.lock, Gopkg.toml, Makefile, build/testing.go, modules/consensus/consensusset.go, modules/gateway/rpc_test.go, persist/boltdb_test.go, persist/persist_test.go, vendor/github.com/bgentry/speakeasy/.gitignore, vendor/github.com/bgentry/speakeasy/LICENSE, vendor/github.com/bgentry/speakeasy/LICENSE_WINDOWS, vendor/github.com/bgentry/speakeasy/Readme.md, vendor/github.com/bgentry/speakeasy/example/main.go, vendor/github.com/bgentry/speakeasy/speakeasy.go, vendor/github.com/bgentry/speakeasy/speakeasy_unix.go, vendor/github.com/bgentry/speakeasy/speakeasy_windows.go
=> enable and configure Travis CI

sync/threadgroup_test.go, sync/trymutex_test.go
closes #82
changes merged from Sia@21b1a98bc99ea424e288660b35653631fbbcf754
=> merge desired sia/sync changes into rivine/sync

api/api.go, api/wallet.go, doc/API.md, doc/api/Wallet.md, doc/api/api.raml, modules/wallet.go, modules/wallet/money.go, rivinec/defaultclient.go, rivinec/walletcmd.go
There is no check on the size of the arbitrary data since I could not find a reference to a maximum size (thought there was one). If the data is too large, then the transaction will be rejected by the transaction pool anyway so this isn't an issue I think.
Closes #117
=> add a registerdata command

modules/transactionpool/standard.go, modules/wallet/seed.go, types/block.go, types/currency.go, types/currency_test.go, types/signatures.go, types/signatures_test.go, types/transactions.go, types/transactions_test.go, types/validtransaction.go
Don't squash.
Wip of #79
The work is not done yet but I think the change would become unmanageable if it would be.
=> sync types package with sia until 53288f0ade137456fa6e03a2ed430528d8641ac4

doc/atomicswap/atomicswap.md
=> add atomic swap technical/example doc

doc/datareplication.md, pkg/client/walletcmd.go
=> Make namespace a separate argument in registerdata

modules/blockcreator/proofofblockstake.go, modules/consensus/block_validation.go, modules/wallet/transactions.go, pkg/client/walletcmd.go, pkg/daemon/server.go, types/block.go, types/block_test.go, types/constants.go
=> make it possible to define custom tx fee beneficiary

modules/consensus/validtransaction.go, modules/transactionpool/standard.go, types/signatures.go, types/transaction_decoder.go, types/transactions.go, types/transactions_test.go, types/validtransaction.go, types/validtransaction_test.go
=> refactor code as to allow support of alt. txn versions

modules/consensus/validtransaction.go, modules/gateway/peers.go, modules/transactionpool/standard.go, types/signatures.go, types/transaction_decoder.go, types/transactions.go, types/transactions_test.go, types/validtransaction.go, types/validtransaction_test.go
=> merge dev 1.0.3 into master

api/wallet.go, modules/wallet.go, modules/wallet/encrypt.go, modules/wallet/encrypt_test.go, modules/wallet/seed.go, modules/wallet/seed_test.go, modules/wallet/wallet_test.go, pkg/client/defaultclient.go, pkg/client/walletcmd.go
=> add capability to recover wallet from existing seed

api/explorer.go
=> add hex encoding of blocks/txns in explorer api

Makefile, modules/consensus/accept_test.go, modules/consensus/accept_txntypes_test.go, modules/consensus/block_validation_test.go, modules/consensus/consensusset_bench_test.go, modules/consensus/consensusset_test.go, modules/consensus/database.go, modules/consensus/diffs_test.go, modules/consensus/persist_legacy.go, modules/consensus/persist_legacy_test.go, modules/consensus/persist_test.go, modules/consensus/processedblock_test.go, modules/consensus/proofofblockstake_test.go, modules/consensus/subscribe_test.go, modules/consensus/synchronize_ibd_test.go, modules/consensus/synchronize_test.go, modules/consensus/validtransaction_test.go, modules/explorer/explorer_test.go, modules/explorer/info_test.go, modules/explorer/persist.go, modules/explorer/persist_legacy.go, modules/explorer/persist_legacy_test.go, modules/explorer/update_test.go, persist/boltdb.go, types/block_test.go
closes #301
ensure that all buckets have the data in the new format
=> update consensus/explorer db versions

modules/consensus/diffs.go, modules/consensus/validtransaction.go, types/constants.go, types/transaction_controller.go, types/transactions.go, types/validtransaction.go, types/validtransaction_test.go
=> limit arbitrary data size to 83 bytes by default

crypto/signatures.go, modules/blockcreator/proofofblockstake.go, modules/wallet/transactionbuilder.go, modules/wallet/wallet.go, pkg/client/atomicswap.go, types/unlockcondition.go
fixes threefoldfoundation/tfchain#102
=> fix panic which can occur when locking while in the middle of using the wallet

types/transactions.go, types/transactions_test.go
broken since commit 59140e9737494558cf90392ba10881430ecc2663
fixes threefoldfoundation/tfchain#134
might also be of relevance for #397 and threefoldfoundation/tfchain#133
=> fix output/txn ID computation

api/explorer.go
add the the unlockhashes for parent blockstake/coin outputs,
as well as all coin/blockstake outputs
=> add unlockhashes to explorer transactions

api/explorer.go, modules/explorer.go, modules/explorer/database.go, modules/explorer/info.go, modules/explorer/persist.go, modules/explorer/persist_legacy.go, modules/explorer/update.go
closes #420
this commit upgrades the explorer db version from 1.0.5 to 1.0.8,
while staying compatible with the explorer db version of 1.0.5
=> index multisig addresses to wallet addresses in explorer

modules/consensus/synchronize.go
=> stop IBD if one OB peer is synced and no blocks are incoming

pkg/api/explorer.go, pkg/client/explore.go
closes #475
the /explorer/hashes/:hash now supports the query parameter 'minheight'
to allow the requester to define a min block height,
returning only blocks/transactions that are either unconfirmed
or are confirmed and registered with a height at least the given min block height value
=> support min-block-height filter when looking up transactions for unlockhash

modules/wallet.go, modules/wallet/encrypt.go, modules/wallet/init.go, modules/wallet/persist.go, modules/wallet/seed.go, modules/wallet/update.go, modules/wallet/wallet.go, pkg/api/wallet.go, pkg/client/walletcmd.go
=> provide unencrypted wallet support

cmd/rivined/daemon.go, modules/blockcreator/blockcreator.go, modules/blockcreator/persist.go, modules/consensus/consensusset.go, modules/consensus/persist.go, modules/gateway/gateway.go, modules/gateway/gateway_test.go, modules/gateway/peers_test.go, modules/gateway/persist_test.go, modules/wallet/encrypt_test.go, modules/wallet/persist.go, modules/wallet/seed_test.go, modules/wallet/wallet.go, modules/wallet/wallet_test.go, persist/log.go, persist/log_test.go, pkg/daemon/config.go
=> Add optional verbose logging

extensions/readme.md
as requested in: https://github.com/threefoldtech/rivine/issues/521
=> Clarification on extensions

modules/gateway/gateway.go
fixes #517
We wait 1 minute before trying to connect again to a bootstrap node which we couldn't connect to.
=> Adds retry loop for connecting to bootstrap nodes

modules/blockcreator/blockmanager.go, modules/transactionpool.go, modules/transactionpool/accept.go, modules/transactionpool/accept_test.go, modules/transactionpool/transactionpool.go, modules/transactionpool/update.go
always validate in context of the entire cs/txpool state
closes #563
=> remove objects/handleConflicts code in txpool

modules/transactionpool/accept.go, modules/transactionpool/subscribe.go, modules/transactionpool/transactionpool.go, modules/transactionpool/update.go
broken since our txpool conflict update
=> preserve txpool tx ordering in tx pool

cmd/rivinecg/cmd/flags.go, cmd/rivinecg/cmd/generate.go, cmd/rivinecg/pkg/config/config_file.go, cmd/rivinecg/pkg/config/github_template.go
added new flag `--no-faucet` , if provided rivinecg will not generate a faucet template.
=> added faucet template generation in rivinecg

pkg/api/explorer.go
Fixes https://github.com/threefoldtech/rivine/issues/532
=> add timestamp and order to transactionlist explorer

modules/wallet/money.go, modules/wallet/transactionbuilder.go, modules/wallet/update.go
closes https://github.com/threefoldtech/rivine/issues/587 & https://github.com/threefoldtech/rivine/issues/483
=> fix issue in transactionbuilder

modules/gateway/gateway.go, modules/gateway/upnp.go
I know that checking if g.threads.IsSTopped  is easier but I prefer to use more standard go functionality instead of the next programmer having to know the custom sync code and structures.
=> Do not continue IP discovery if the gateway is closed

extensions/authcointx/csplugin.go
If the `Reverse` bool is provided we reverse the logic of this plugin.
This means that by default all addresses are authorized and can send and receive.
=> add reverse option to authcointx plugin
