doc/examples/offline_transaction/offline_transaction.go
modules/explorer/update.go

fixes #61:
It seems that the miner reward was not added to the `CoinOutput` bucket of the explorer DB. When info was then requested about a block or transaction in which a miner fee was spent, the explorer check to see if the output being spent actually existed failed, causing a panic in debug mode. These missing outputs are now added in the ProcessConsensusChange method. (Or removed, if blocks get reverted)
I also enabled the spending of miner fees in the offline transaction example, as this now no longer causes a crash due to the explorer panic on subsequent invocations of the example on the same chain (in case a miner fee was spent)

Fix explorer minerfee appearance

---

modules/blockcreator/blockcreator.go
modules/blockcreator/proofofblockstake.go

Solve a reasonably frequent race condition when the block creator tries to solve a block just as it receives a consensus change. Also avoid creating blocks until we are fully synced to save some  system resources that would otherwise be wasted on useless blocks, especially during IBD on a new node (probably nothing major).
I feel that it is better to cache the synced state on the blockcreator struct, as this avoids a (relatively) expensive readlock to check the consensus sync state itself. Also, it only ever switches from false to true once we caught up after a (re)start of rivined.
As for the readlock on the `solveBlock` metod, I'm not sure if it is best to readlock here just to lock the height variable from the consensus change, or if we should lock in the parent method (`SolveBlocks`), …

Fix blockcreator race

---

persist/log_test.go

skip TestLogger as the sync syscall can take >5s

---

pkg/client/defaultclient.go
pkg/client/walletcmd.go

We did not want to use the seed as a password initializing a
wallet when the user did no provide one.
So we have removed the password -p flag, now every wallet initialization
will ask the user for a password and a verification.
In my machine setting the password complains with **Error when encrypting wallet: error when calling /wallet/init: The number of bits must be divisible by 32** but the wallet is initialized and with the password selected.

Issue 119: Don't use seed as password

---

doc/api/api.raml

The file api.raml was outdated, some functions were not available and
some other were not reflected in the api.raml file
We have updated all the calls, and return values
I've removed the  /{addr} url as I have been unable to find a handler in the code, and the default one points to a 400 error page, So I presumed that this was some outdated remanent in the file
closes #146

Update of the api.raml file

---

api/api.go
api/consensus.go
api/consensus_test.go
doc/api/api.raml
modules/consensus.go
modules/consensus/consensusset.go
modules/wallet/wallet_test.go
pkg/client/consensuscmd.go
pkg/client/defaultclient.go
types/transactions.go
types/transactions_test.go

+ add TransactionShortID type (closes #149);
+ add GetTransactionAtShortID function to ConsensusSet:
+ this is also exposed as the '/consensus/transactions/:shortid' endpoint;
+ the newly exposed endpoint is also available as
'rivinec consensus transaction <shortID>';

add transaction short ID and consensus-get-transaction func

---

pkg/daemon/commands.go
pkg/daemon/daemon.go
pkg/daemon/daemon_test.go
pkg/daemon/server.go

Closes #102 
Partial work for #103 
Mainly refactor the StartDaemon method to no longer depend on a config struct, but actually take all the required variables as params. Also added a password param, so we can provide a password through other means in the future. The password is still prompted if it is required but not set yet.

Update startdaemon to use params instead of a config struct

---

cmd/rivined/main.go
modules/blockcreator/blockcreator.go
modules/blockcreator/persist.go
modules/consensus/consensusset.go
modules/consensus/persist.go
modules/explorer/explorer.go
modules/gateway/gateway.go
modules/gateway/gateway_test.go
modules/gateway/persist_test.go
modules/transactionpool/transactionpool.go
modules/wallet/encrypt_test.go
modules/wallet/persist.go
modules/wallet/seed.go
modules/wallet/seed_test.go
modules/wallet/wallet.go
modules/wallet/wallet_test.go
persist/log.go
persist/log_test.go
pkg/daemon/commands.go
pkg/daemon/daemon.go
profile/profile.go
types/blockchain.go

used to be the hardcoded Rivine(d) name and build.Version,
now it is all done using a non-global info struct
fixes #118

use blockchain-specific name and version

---

api/api.go
api/consensus.go
doc/api/api.raml
modules/consensus.go
modules/consensus/applytransaction.go
modules/consensus/consensusdb.go
modules/consensus/consensusset.go
modules/consensus/diffs.go
modules/consensus/processedblock.go
modules/wallet/wallet_test.go
pkg/client/consensuscmd.go
types/transactions.go
types/transactions_test.go

Allow lookup of a transaction using is regular/long ID
Remove explorer module dependency when doing a transaction lookup, the returned value is now the raw transaction, not the explorer module transaction
Closes #182 
Closes #188 
Closes #204

Lookup transactions with long id

---

Makefile
release.sh

fixes #282 
result
```
$ git checkout v1.0.2 && hack_makefile() && make release-std
go build -ldflags '-X github.com/rivine/rivine/build.rawVersion=v1.0.2' -o /Users/glendc/go/bin/rivined ./cmd/rivined
go build -ldflags '-X github.com/rivine/rivine/build.rawVersion=v1.0.2' -o /Users/glendc/go/bin/rivinec ./cmd/rivinec
$ rivined version
Rivine Daemon v1.0.2
Rivine Protocol v1.0.2
```
> version only contains tag when exactly on the tag (e.g. `v1.0.2`)
```
$ git checkout master && make release-std
go build -ldflags '-X github.com/rivine/rivine/build.rawVersion=v1.0.2-bdfee0f' -o /Users/glendc/go/bin/rivined ./cmd/rivined
go build -ldflags '-X github.com/rivine/rivine/build.rawVersion=v1.0.2-bdfee0f' -o /Users/glendc/go/bin/rivinec ./cmd/rivinec
$ rivined version
Rivine Daemon v1.0.2-bdfee0f …
```

add version when installing using a supported make target

---

api/api.go
api/explorer.go
modules/explorer.go
modules/explorer/info.go

Expose some basic stats about a range of blocks through the explorer. This allows us to create some (basic) graphs to have a visual representation of the chain at some point in time. Datapoints are returned based on block heights (not time).
Also moved the (debug) daemon constants handler to the explorer, so they can be leveraged to calculate percentages of current active BS vs max active BS, for example.

Close #288: Add explorer api support to get graph datapoints

---

types/signatures.go
types/transaction_controller.go
types/transactions.go
types/transactions_test.go
types/unlockcondition.go
types/unlockcondition_test.go

closes #293
Unknown versions of transactions, conditions and fulfillments
can no longer be decoded, as these are no longer supported.
The only way to add a new/alternative txn/condition/fulfillment
is to ensure the majority of block stake holders has this update
and agrees with it.

remove support for unknown versions

---

README.md
doc/transactions/light_wallet.md
doc/transactions/transaction.md
doc/transactions/unlockhash.md
types/signatures_doc_test.go

+ add light_wallet.md: used as a guide for anyone wishing to
implement their own light wallet/client
+ documents timelock conditions (fixes #297)
+ documents and explains v1 transactions, explains it deprecates
v0 transactions, and updates any outdated information (fixes #296)
+ add unit tests to ensure our signture psuedocode is correct (closes #315)

update transaction docs

---

api/wallet.go
modules/wallet.go
modules/wallet/money.go
modules/wallet/money_test.go
pkg/client/walletcmd.go
pkg/client/walletcmd_test.go

closes #323
also removes the --legacy and --locktime flags,
sending legacy transactions has no value so no longer needed,
and --locktime is no longer needed as you can use this feature now
by sending a raw JSON-encoded condition

support raw (JSON) conditions in the wallet send commands

---

types/unlockcondition.go
types/unlockcondition_test.go

+ At least 2 unlockhashes are required in the multisigcondition, as otherwise there is no point in using the multisig condition (used to be just 1, but for that people should use just an unlockhash condition);
+ Only pubkey unlockhashes are allowed, prior to this update no unlockhash type check happened;
+ At least 1 pair is required in multisigfulfillment (OK, this was already implicitly true, due to the condition requirement, and the fact that otherwise a valid condition cannot be fulfilled, but now we have a cheap early check);

make multisig condition/fulfillment standard checking stricter

---

modules/wallet/outputs.go
modules/wallet/update.go
pkg/client/walletcmd.go

Add support for multisig input and outputs when listing transaction and (un)locked outputs
Fix #356 
Fix #358

Add support for multisig in transaction and output list

---

api/consensus.go
api/wallet.go
pkg/cli/flag.go
pkg/cli/flag_test.go
pkg/client/atomicswap.go
pkg/client/defaultclient.go
pkg/client/flag.go
pkg/client/flag_test.go
pkg/client/http.go
types/transactions_test.go
types/unlockcondition.go
types/unlockcondition_test.go

+ only check timelock for atomic swap refunds (fixes #351, fixes threefoldfoundation/tfchain#112)
+ align atomic swap cli commands terminology (fixes #334):
+ rename atomicswap claim to atomicswap redeem (fixes #347);
+ remove amount parameter in redeem/refund commands (fixes #348);
+ align the audit command where possible;
+ change help to update terminology;
+ change hashed secret to secret hash;
+ rename atomicswap audit to atomicswap auditcontract;
+ rename sender to initiator;
+ rename receiver to participator;
+ fix bugs in atomic swap commands:
+ ensure secret can be extracted from atomic swap secret (fixes threefoldfoundation/tfchain#116);
Atomic Swap commands usage and help now is as follows:
```
Usage:
rivinec atomicswap [command]
Available Commands:
auditcontract Audit a …
```

atomic swap improvements and fixes

---

pkg/client/atomicswap.go
pkg/client/defaultclient.go

+ closes #365: yes/no questions can be skipped by
passing a -y/--yes flag to the relevant atomic swap command(s)
+ closes #366: output of atomic swap CLI commands can be encoded
in JSON, as an alternative to the already existing human format
+ atomic swap commands now print everything on Stderr, except for the actual output (including the interactive feedback/questions);
+ improve the exit codes: errors because of misuse of a command are now always killing the process with exit code usage (`64`), and when the process gets killed because of cancellation by the "user", it is done so using exit code `3`;

make atomicswap CLI commands usable in an automated environment

---

modules/consensus/diffs.go
modules/consensus/validtransaction.go
modules/transactionpool.go
modules/transactionpool/accept.go
modules/transactionpool/standard.go
types/constants.go
types/signatures.go
types/signatures_test.go
types/transaction_controller.go
types/transaction_legacy.go
types/transaction_legacy_test.go
types/transactions.go
types/transactions_test.go
types/unlockcondition.go
types/unlockcondition_test.go
types/validtransaction.go
types/validtransaction_test.go

+ Legacy Transactions (v0) can now be overwritten/unregistered,
just like any other transaction;
=> This is a pure Golang-API change, nothing in the protocol or encoded format changed (proven by unchanged tests such as https://github.com/rivine/rivine/blob/111d9d3e2e72ba9c88a368913b13072d2e5ec386/types/transactions_test.go#L156);
+ as a design consequence, TransactionControllers now can choose completely how to marshal the transaction data in binary format. It's up to the implementation to define if the length if to be prefixed or not. Even though it might be recommended, it is not enforced any longer;
+ The standard check of conditions and fulfillment is now applied in both consensus set,
and in the transaction pool, rather than the latter alone (fixes #393);
+ Transaction pool and …

improve strictness of consensus and demote legacy transactions

---

modules/transactionpool.go
modules/transactionpool/accept.go
modules/transactionpool/transactioncache.go
modules/transactionpool/transactionpool.go
modules/transactionpool/update.go

Rebroadcast a transaction if it is stuck in the pool. A transaction is considered stuck if a new block is accepted in consensus, and the txn itself is not approved in said block. To avoid spamming the network, we broadcast a transaction only a limited number of times, and only every few blocks. Right now, we rebroadcast 4 times (thus 5 total broadcasts if we also count the original broadcast), and broadcast once every 3 blocks. We also only broadcast if the consensus indicates we are currently synced, to avoid spamming a txn in rapid succession to the network if the deamon is syncing (as we can't know if the txn is still valid anyway).
The pool does not "propagate" a rebroadcast, to avoid too much network spam. There is also no benefit: for a pool to REbroadcast, it would already need to …

Fix #286: reboroadcast txns

---

cmd/rivined/daemon.go
modules/blockcreator/blockcreator.go
modules/consensus.go
modules/consensus/consensusset.go
modules/wallet/wallet_test.go

Part of issue https://github.com/threefoldfoundation/tfchain/issues/303
Added start method on:
- consensusset
And registered api endpoint before starting this module. This allow us the register the api before doing any long running tasks which are needed before starting the consensusset.

Unblocked API on startup

---

modules/gateway/peers.go

Adds some debug logs when a peer disconnects / connects. Not sure how to reproduce issues with adding / removing peers to check if logs are sufficient.
Closes #488.

added gateway debug logging to connect / disconnect peer

---

modules/consensus/diffs.go
modules/consensus/validtransaction.go
modules/transactionpool/standard.go
types/unlockcondition.go
types/validtransaction.go
types/validtransaction_test.go

Require that all transactions define a high enough fee (except for transactions explicitly created by block creators for the POBS protocol). Previously it was possible to create transactions without fees (though 0 value fees were correctly rejected)

Fix #504: Require miner fees for regular txns

---

cmd/rivined/daemon.go
modules/consensus/consensusset_test.go
modules/gateway/consts.go
modules/gateway/gateway.go
modules/gateway/gateway_test.go
modules/gateway/peers.go
modules/gateway/peers_test.go
modules/gateway/persist_test.go
modules/gateway/rpc.go
modules/gateway/rpc_test.go
modules/wallet/wallet_test.go

Replace the sleep rate limiting implementation with a token bucket version. See #564 for details
Fix #519 
Close #564

Improve RPC rate limiting

---

extensions/authcointx/csplugin.go
extensions/minting/minting.go
modules/consensus.go
modules/consensus/diffs.go
modules/consensus/fork.go
modules/consensus/plugin.go
modules/consensus/plugin_test.go
modules/consensus/validators.go
modules/consensus/validtransaction.go

remove consensusStateGetter, no longer required,
and use a special ConsensusBlock/Transaction that contains also
the coin outputs and blockstake outputs used as inputs

refactor validation interface of consensus

---

modules/consensus/accept.go
modules/consensus/consensusset.go
modules/consensus/proofofblockstake.go

Cache the block id's and their matching parent block id's. This removes
about 2256 (in default configuration) database reads, which would read
an entire block every time, possibly loading more than a gigabyte
of data over and over again. This lazy loading removes the need to do
that, apart from the first block which will need to populate the cache.
In case a new daemon is started without any blocks, there will actually
be no database reads to calculate the stake modifier at all until the
daemon is stopped and restarted.

Improve stake modifier calculation

---

Makefile
persist/persist.go
persist/persist_test.go

also removed two unit tests from the persistent pkg,
one of the two tests failed, while fixing I realized
that the code it was testing was only used in these
two tests, hence deleting it all seemed like the more
economical decision
fixes #623

add test-related Makefile targets back

---

Makefile

if git describe fails we fall back on version : `v0.1-{commitHash}`

fixes travis build on example/rivchain job, #630

---

extensions/authcointx/csplugin.go

This fixes a bug where the information about an address, if it does not exist in our bucket is not reversed properly.

fixes bug in authcoin status of an address
